### ISSUE TITLE
Permission Error for makeDependencies

### ISSUE THREAD

**Issue by danielstruck** [SidneyTowers/TrackerSystem#14]
The line
**make -j...**
in makeDependencies cannot complete because it requires write permission to a bunch of stuff. This results in make terminating once the error is thrown.

**Comment by SidneyTowers** [comment]
Is this still an issue? As that line is provided as a sudo command, so there should be no permission issues whatsoever.

**Comment by danielstruck** [comment]
Yes, I tried to change it to sudo, but it did not work. The commands that this makefile runs are not sudo and they are the ones with the permission error.

**Comment by SidneyTowers** [comment]
Potentially fixed. Updated the ReadMe file, so follow that. Worked on both an ubuntu virtual box and a debian linux running on a chromebook. Let me know if it now works for you.
